name: CI actions
on: [pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.2.1
      - name: Install dependencies
        run: poetry install
      - name: Check formatting with Black
        run: poetry run black --check --diff .
      - name: Lint with flake8
        run: flake8 . --count --statistics --show-source

